services:
  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi #image name
    build:
      context: .
      dockerfile: src/CatalogService/API/Dockerfile #path to Dockerfile
    env_file:
      - src/CatalogService/API/.env
    ports:
      - 5001:8080 # Exposes port 8080 of the container on port 5000 of the host
    depends_on:
     - sqlserver #depends on sqlserver service
    environment:
     - ASPNETCORE_ENVIRONMENT=Development #sets environment variable
    networks:
     - app-network #connects to app-network
    restart: on-failure #restarts the container on failure

  sqlserver: 
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "${SQLServer_Password}"
      ACCEPT_EULA: "Y"        
    ports:
      - 1433:1433
    volumes:
     - sqlvolume:/var/opt/mssql #persists database data
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE} #database name
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME} #root username
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD} #root password
    ports:
      - 27017:27017        # Exposes MongoDB default port
    volumes:
      - mongodata:/data/db  #persists MongoDB data
    networks:
      - app-network
  
  cart:
    image: ${DOCKER_REGISTRY-}cart
    container_name: cart
    build:
      context: .
      dockerfile: src/CartServices/API/Dockerfile
    env_file:
      - src/CartServices/API/.env
    depends_on:
     - mongodb
    ports:
      - 5002:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
     - app-network
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin #default username
      RABBITMQ_DEFAULT_PASS: admin123 #default password
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq #persists RabbitMQ data
    networks:
      - app-network

  identityserverapi:
    image: ${DOCKER_REGISTRY-}identityserverapi
    container_name: identityserverapi
    build:
      context: .
      dockerfile: src/IdentityServerApi/IdentityServerAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5004:8080
    networks:
      - app-network
    restart: on-failure

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    container_name: apigateway
    build:
      context: .
      dockerfile: src/ApiGateway/APIGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
     - catalogapi
     - cart
     - identityserverapi
    ports:
      - 6001:8080
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:

volumes:
  sqlvolume:
  mongodata:
  rabbitmqdata:  
